#!/usr/bin/env sh

# Load scripting additions
yabai -m config scripting_addition payload

# General settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90

# Window borders
yabai -m config window_border                on
yabai -m config window_border_width          3
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff555555

# Tiling settings
yabai -m config layout                       bsp
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10

# Automatically balance windows to maintain even sizes
yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.50
yabai -m config split_type                   auto
yabai -m config auto_raise                   on

# Hotkeys using skhd to manage windows and spaces
# These commands need corresponding entries in your skhdrc file

# Start yabai (it is assumed that the service is managed by brew services)
brew services start koekeishiya/formulae/yabai

# Apply the configuration
yabai -m config --load

# Make the configuration executable
chmod +x ~/.yabairc

